# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hellotext Help
email: info@hellotext.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://help.hellotext.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  hellotext

jekyll-minifier:
  uglifier_args:
    harmony: true


# Build settings
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-postcss
  - jekyll-redirect-from
  - jekyll-minifier

languages: ["en", "es"]
exclude_from_localizations: []

algolia:
  application_id: WURCDLSM2D
  index_name: hellotext-help
  search_only_api_key: 32a31859dbe7f63f5cd8ff11af0c8b70
  files_to_exclude:
    - _i18n/.yml

collections:
  topics:
    order:
      - getting-started.html
      - best-practices.html
      - campaigns.html
      - audience.html
      - numbers.html
      - team.html
      - journeys.html
      - captures.html
      - billing.html
      - integrations.html
      - developers.html
      - editor.html
    output: true
  campaigns:
    order:
      - creating-a-campaign.md
      - campaign-reporting.md
    output: true
  audience:
    output: true
  numbers:
    order:
      - acquiring-a-number.md
      - migrating-an-existing-number.md
      - acquiring-a-keyword.md
      - obtaining-an-exclusive-shortcode.md
    output: true
  team:
    order:
      - understanding-team-roles.md
      - assigning-conversations.md
      - transferring-ownership.md
    output: true
  getting-started:
    output: true
    order:
      - setting-up-your-business.md
      - frequent-questions.md
      - tips-and-best-practices.md
      - setting-up-your-cname-alias.md
  billing:
    output: true
  captures:
    output: true
    order:
      - qr-codes.md
      - instagram-story.md
  journeys:
    output: true
    order:
      - getting-started-with-journeys.md
      - custom-journey.md
  integrations:
    output: true
  developers:
    output: true
    order:
      - tracking-events.md
      - tracking-on-campaigns-and-journeys.md
      - tracking-unidentified-customers.md
      - external-tracking.md
      - api.md
  editor:
    output: true
    order:
      - get-started.md
      - links.md
      - tags.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
